# -*- coding: utf-8 -*-
"""Single_Turbine_Model1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dYxEgVfXHsiW-UAj2rX6o-bWk-t4p4lz
"""

import pandas as pd
import matplotlib.pyplot as plt

"""Turbine Information:

Rated Power: 25 kW (7.7 m/s)
Cut in Speed: 2.5 m/s (0.855 kW)
Cut out Speed: 20 m/s (437 kW)

Blade length: 7.6 m, S_area = 181 m2, Hub_Height = 16 m

"""

windspeed = pd.read_csv('Wind_Speed.csv')
windspeed

ws = windspeed.iloc[:,4:5]
ws

ws.describe()

# In case you have wind speed data with km/h unit
#def meter_second(x):
 # return x/3.6

AD = 1.275 # kg/m3
BZ = 0.593
Area = 181 #m2
Eff = 0.8

def wind_p(x):
  return (0.5*AD*Area*(x**3)*BZ*Eff)/1000

Wind_Power = wind_p(ws)
Wind_Power

Wind_Power.rename(columns = {'WS10M':'Power_Output(kW)'},inplace=True)
Wind_Power

#wind_p(2.5)
#wind_p(20)

Wind_Power.loc[(Wind_Power['Power_Output(kW)']>=25)&(Wind_Power['Power_Output(kW)']<437)] = 25
Wind_Power.loc[Wind_Power['Power_Output(kW)']>=437] = 0
Wind_Power.loc[Wind_Power['Power_Output(kW)']<=0.855] = 0

"""Visualization

Wind Power Output
"""

plt.plot(Wind_Power,c = 'b')
plt.xlabel('hours')
plt.ylabel('Power Output (kW)')
plt.show()

"""Power Curve"""

DF = pd.concat([Wind_Power,ws],axis=1)
DF.sort_values(by=['WS10M'],ascending=True,ignore_index=True,inplace=True)
DF

plt.plot(DF['WS10M'],DF['Power_Output(kW)'],c = 'r')
plt.xlabel('Wind Speed (m/s)')
plt.ylabel('Power (kW)')
plt.show()