# -*- coding: utf-8 -*-
"""Single_Turbine_Model2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12qiS1xL9udF3OGo7NtX-AWk-LYWvzNJI
"""

!pip install windpowerlib

import pandas as pd
import matplotlib.pyplot as plt
from windpowerlib import ModelChain,WindTurbine
from windpowerlib import data as wt

"""**Reading Weather Data**"""

Weather_Data = pd.read_csv('weather_montreal.csv',index_col=0,header=[0,1],
                           date_parser=lambda idx:pd.to_datetime(idx,utc=True))
Weather_Data

"""**Wind Turbine Selection**"""

Turbine_lib = wt.get_turbine_types(print_out=False)

Selected_turbine = {'turbine_type':'E48/800','hub_height': 60}
W_Turbine = WindTurbine(**Selected_turbine)

Tubine_Sub_Models = {
    'wind_speed_model': 'hellman',          #'logarithmic' this one is the default
                                            # 'interpolation-extrapolation'
    'density_model': 'ideal_gas',           # 'barometric' (default)
                                            # 'interpolation-extrapolation'
    'temperature_model':'linear_gradient',  # 'interpolation-extrapolation'
    
    'power_output_model' :'power_coefficient_curve',  # 'power_curve' is the default

    'density_correction': True,             # False is default
    'obstacle_height': 0,                   # default is 0
    'hellman_exp': 0.25
}

Model = ModelChain(W_Turbine,**Tubine_Sub_Models).run_model(Weather_Data)

Turbine_Power_Output = (Model.power_output)/1000
Turbine_Power_Output

plt.plot(Turbine_Power_Output,color = 'blue')
plt.xlabel('Date')
plt.ylabel('Power - kW')
plt.show()