# -*- coding: utf-8 -*-
"""Wind Distribution.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FbV1T-NC1QXFZIN6TTunIpsbfZHqKp95
"""

import pandas as pd
import matplotlib.pyplot as plt
import scipy.special as sc
import numpy as np
import math

WS = pd.read_csv('Wind_Speed.csv')
WS = WS.iloc[:,4:5]

def weib(x,c,k):
    return (k / c) * (x / c)**(k - 1) * np.exp(-(x / c)**k)

k= (math.sqrt(np.mean(abs(WS - np.mean(WS))**2))/np.mean(WS))**-1.089
# Gamma(n)=(n-1)! but here we need logarithm of the function so we use gammaln and then exp of it will be used for calculating scale factor
Gamma_F = math.exp(sc.gammaln(1+(1/k)))
c = (np.mean(WS)/Gamma_F)

Weibull = weib(WS,c,k)
Weibull_DF = pd.DataFrame(Weibull).rename(columns={"WS10M":"Probability"})
Weibull_DF

WS

N=8760
colors = np.random.rand(N)
plt.scatter(WS,Weibull,c=colors, zorder=2)
plt.xlabel("Wind Speed (m/s)")
plt.ylabel("Probability")
plt.title("Weibull Distribution")
plt.show()